### PR TITLE
feat(azcopy.hcl): add version 10.16.2

### PR DESCRIPTION
**Pull request by usrme**

### CODE REVIEW

**Comment by alecthomas** [comment]
Tests are failing, I think because you shouldn't have `release` in the version.

**Comment by usrme** [comment]
> Tests are failing, I think because you shouldn't have `release` in the version.

Oh, man, I initially very hastily pushed this and didn't come back to check the test results :disappointed:

**Comment by usrme** [comment]
Looks like it now tried to test _all_ the packages and ran into issues regarding that :thinking:

**Comment by alecthomas** [comment]
You need to rebase your PR against master.

**Comment by usrme** [comment]
This is just getting out of hand by now. I'll start from scratch.

**Comment by alecthomas** [comment]
Hehe ok :)

**Pull request closed without merging**
