### PR TITLE
feat(azcopy.hcl): add version 10.20.0

### PR DESCRIPTION
**Pull request by usrme**

### CODE REVIEW

**Comment by usrme** [comment]
Looks like they changed the format of the URL going forward and what's worse it looks like previous packages aren't available from neither :face_exhaling:

**Review by alecthomas — APPROVED** [review]

**Comment by usrme** [comment]
> Looks like they changed the format of the URL going forward and what's worse it looks like previous packages aren't available from neither face_exhaling

@alecthomas, should all of the previous releases be removed considering the above and the URL format be adjusted for releases including this new one and the ones going forward?

**Comment by alecthomas** [comment]
I'm still able to install the old versions, or at least 10.19.0:
```
🐚 ~/dev/overmind $ hermit install azcopy
info:azcopy-10.19.0:install: Installing azcopy-10.19.0
```

**Comment by usrme** [comment]
Yeah, my bad. I just saw that they just added an additional segment: https://azcopyvnext.azureedge.net/releases/release-10.20.0-20230727/azcopy_linux_amd64_10.20.0.tar.gz. 

What's the canonical way to keep the old versions on the previous URL format and the new ones with the new one? :thinking:

**Comment by alecthomas** [comment]
No worries!

Create a version block for all the old versions, containing the moved old aource fields

**Comment by alecthomas** [comment]
That won't work for this package though. If the new URL is similar to the old one you might be able to use another variable to differentiate between the old and new, but if that's not possible I think you're going to have to fully expand all the URLs in the old version blocks :(

**Comment by usrme** [comment]
I managed to get everything sorted in a much easier way with commit [eff16d1](https://github.com/cashapp/hermit-packages/pull/365/commits/eff16d15922bd8e761f438c1a3d65586a8c3fc40). Let me know what you think.

**Review by alecthomas — APPROVED** [review]

**Comment by alecthomas** [comment]
Nice approach I like it!

Would you mind running `hermit manifest add-digests azcopy.hcl`?

**Comment by usrme** [comment]
> Nice approach I like it!
> 
> Would you mind running `hermit manifest add-digests azcopy.hcl`?

Done!

**Comment by alecthomas** [comment]
Thanks!

**Pull request merged**
