### PR TITLE
feat: enable auto-version for Kustomize

### PR DESCRIPTION
**Pull request by mightyguava**

### CODE REVIEW

**Review by alecthomas — APPROVED** [review]

**Comment by alecthomas** [comment]
Did you verify it works? Activate this repo as a Hermit env, then run `hermit manifest autoversion kustomize.hcl`

**Comment by mightyguava** [comment]
Ah, it both does and doesn't work. It does properly skip over the bad version. But hermit only looks at the newest release so it just doesn't do anything.

**Comment by mightyguava** [comment]
https://github.com/cashapp/hermit/pull/309

**Comment by mightyguava** [comment]
The linked PR works

```
-version "4.4.1" {
+version "4.4.1" "4.5.7" {
   source = "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${version}/kustomize_v${version}_${os}_${arch}.tar.gz"
```

**Pull request merged**
