### PR TITLE
Add Gradle 8.7

### PR DESCRIPTION
**Pull request by eric-labelle**
Release Notes: https://docs.gradle.org/8.7/release-notes.html
Checksum: https://gradle.org/release-checksums/#v8.7

### CODE REVIEW

**Comment by eric-labelle** [comment]
FYI @alecthomas

**Review by alecthomas — APPROVED** [review]

**Comment by alecthomas** [comment]
Thanks!

**Comment by staktrace** [comment]
waah so fast, didn't even wait for the auto-versioner!

**Comment by eric-labelle** [comment]
> waah so fast, didn't even wait for the auto-versioner!

Oops. Lol I always add them myself. Wasn't aware that there was something automated for that 🧐

**Pull request merged**
