### PR TITLE
Add Maestro CLI package

### PR DESCRIPTION
**Pull request by kirillzh**
Maestro is a tool to run mobile UI tests.

https://maestro.mobile.dev/

Resolves https://github.com/cashapp/hermit-packages/issues/407

### CODE REVIEW

**Comment by alecthomas** [comment]
Do these binaries run on all platforms?

**Comment by kirillzh** [comment]
> Do these binaries run on all platforms?

Good callout. The [docs](https://github.com/mobile-dev-inc/maestro/blob/main/CONTRIBUTING.md#architectural-considerations) mention that it's supposed to work on Mac OS, Linux, and Windows. I see the release provides with two binaries:
- `bin/maestro` - I assume this one is for mac and linux
- `bin/maestro.bat` - I guess that's the one for windows which current proposed manifest doesn't support? @lyonlai @alecthomas any guidance on how to update the manifest appropriately? I haven't seen any examples of current packages that unpack `.bat` binaries, and don't really have windows myself to test it out.

**Comment by alecthomas** [comment]
Hermit only supports Linux and Mac, so having just `bin/maestro` should be fine. I'm not sure if the .bat file is executable, but I'd probably explicitly specify `bin/maestro` as the binary.

**Comment by kirillzh** [comment]
> Hermit only supports Linux and Mac, so having just `bin/maestro` should be fine. I'm not sure if the .bat file is executable, but I'd probably explicitly specify `bin/maestro` as the binary.

Sound good, pushed the change 👍🏻

**Review by alecthomas — APPROVED** [review]

**Pull request merged**
