### PR TITLE
feat(gcloud.hcl): add newer versions of 'google-cloud-sdk'

### PR DESCRIPTION
**Pull request by usrme**
There may be a way to set up `auto-version` with `xpath` similar to how it is done for [Zig](https://github.com/cashapp/hermit-packages/blob/master/zig.hcl) using values from this [release notes page](https://cloud.google.com/sdk/docs/release-notes), but that seemed like a whole bunch of messing about given how wild the mark-up is. Is there a simpler way to set up automatic versioning for this because they release new versions on a pretty regular cadence?

### CODE REVIEW

**Comment by alecthomas** [comment]
Wow you are not wrong, that markup is awful.

The only mechanisms for auto-versioning are xpath and GH releases. This is a bit of a hack, but [this repo](https://github.com/twistedpair/google-cloud-sdk/tags) seems to sync with the SDK. We could auto-version off this...best case it works, worst case it is no worse than it is now.

**Comment by usrme** [comment]
I couldn't let the `xpath` thing go, so I am trying to get that parsed properly. It seems that despite the mark-up being tens of thousands of lines the `<h2>` tags seem to hold the key to solving this. Is there way for me to validate whether the following `auto-version` block indeed returns what I expect, which would be `405.0.0`?

```
  auto-version {
    html {
      url = "https://cloud.google.com/sdk/docs/release-notes"
      xpath = "substring-before(//h2[1]/text(), ' ')"
    }
  }
```

I'm grabbing only the first `<h2>` element as that is the latest version, the text from within it and then only what is before the space.

**Comment by usrme** [comment]
Okay, so I found the `manifest auto-version` command to test this out, but no dice with the above query. I removed version `405.0.0` from the manifest and ran the following:

```console
$ hermit -d -t manifest auto-version gcloud.hcl 
debug: Auto-versioning .../gcloud.hcl
trace: GET https://cloud.google.com/sdk/docs/release-notes
```

Clearly the query isn't working in the same way, but I am unsure how to debug this further.

**Comment by usrme** [comment]
More progress: the fault lies in that the original query returned a single string whereas Hermit ideally expects a list of nodes to iterate over to form a list that can then be ordered, which I assume forms the basis for an auto-versioned bump within the manifest. A query like this is much better `"//h2/text()"`, but I have yet to figure out how to use the `substring-before()` function this way.

**Comment by usrme** [comment]
Okay, it seems that just going without the `substring-before()` function is valid as well as long as the `version-pattern` attribute within the `auto-version` block specifically includes white-space. See the previous commit and let me know if this works for you.

**Review by alecthomas — APPROVED** [review]

**Comment by alecthomas** [comment]
If it works, ship it!

**Pull request merged**
